remote_theme              : "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin     : "default"
name                      : "Jacob Kell"

locale                    : "en-US"
title                     : "Perovskite Solar cells"
subtitle                  : "hi"
layout                    : single
classes                   : wide
